name: Build CI version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - run: rm package-lock.json
      - run: npm --no-git-tag-version version 1.0.${{ github.run_number }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run package
      - uses: actions/upload-artifact@v3
        with:
          path: ./vscode-github-actions-1.0.${{ github.run_number }}.vsix
