name: Pre-Prepare

on:
  workflow_dispatch:
    inputs:
      pull-langugageserver:
        description: "Are there changes to language server?"
        default: false 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      - name: run npm install
          run: npm install @actions/languageserver@latest @actions/workflow-parser@latest --workspaces=false
      - name: revert changes to package.json
          run: git checkout -- package.json
      - name: run npm i
          run: npm i
      - name: create branch
          run: | 
            git checkout -b env.BRANCH_NAME
            git add -A
            git commit -m "automation: update language server"
            git push origin env.BRANCH_NAME
          env: 
            BRANCH_NAME: "update-language-server-${{ github.run_id }}-${{ github.run_attempt}}"
      - name: create pull request
          uses: peter-evans/create-pull-request@v5
          